language: scala

jdk:
    - oraclejdk7

# Use the container-based infrastructure.  Aloha only works on the container-based infrastructure
# because currently, /proc/version in the non-container-based infrastructure doesn't match the VM
# type.  The VM says Ubuntu 12 and /proc/version says redhat.
sudo: false

# Cache the installation of protoc
cache:
    directories:
        - $HOME/protobuf

# VW in aloha-vw-jni needs libboost program options
addons:
    apt:
        packages:
        - libboost-program-options-dev

scala:
    - 2.10.5
    - 2.11.8

before_install:
    - source travis-install-protobuf.sh
    - bash travis-install-aloha-proto.sh
    - source travis-mv-filtered.sh # This is just temporary until a better solution.

# This is just for now until SBT issues are totally fixed.
script:
    - sbt ++$TRAVIS_SCALA_VERSION clean editsource:edit && mv_filtered
    - sbt ++$TRAVIS_SCALA_VERSION test || sbt ++$TRAVIS_SCALA_VERSION test:test-quick || sbt ++$TRAVIS_SCALA_VERSION test:test-quick || sbt ++$TRAVIS_SCALA_VERSION test:test-quick
