#
# Before installing, we need to install protoc 2.4.1 and then checkout and build the aloha-proto project
# in case the current aloha version is using a snapshot.  If it's not using a snapshot, no harm, no foul.

language: scala

jdk:
    - oraclejdk7

sudo: false

cache:
  directories:
  - $HOME/protobuf

addons:
  apt:
    packages:
    - libboost-program-options-dev

scala:
    - 2.10.4

before_install:
    - cat /proc/version
    - source travis-install-protobuf.sh
    - bash travis-install-aloha-proto.sh
