language: scala
scala:
   - 2.10.4
jdk:
  - oraclejdk7

before_install:
    - git clone https://github.corp.eharmony.com/matching/aloha-proto.git
    - cd aloha-proto
    - mvn clean install
    - cd -
install: mvn clean package -DskipTests=false
