language: scala
scala:
    - 2.10.4
jdk:
    - oraclejdk7
#os:
#    - osx
before_install:
    - sudo echo 'Linux version 3.13.0-40-generic (buildd@comet) (gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) ) 69-Ubuntu SMP Thu Nov 13 17:53:56 UTC 2014' > /proc/version
    - cat /proc/version
    - wget https://protobuf.googlecode.com/files/protobuf-2.4.1.tar.gz
    - tar -xzvf protobuf-2.4.1.tar.gz
    - cd protobuf-2.4.1 && ./configure --prefix=/usr && make && sudo make install
    - cd -
    - git clone https://github.com/eHarmony/aloha-proto.git
    - cd aloha-proto
    - mvn clean install
    - cd -
    - cat /proc/version
#install: mvn clean package -DskipTests=false
install: cat /proc/version && cd aloha-core &&  mvn clean test -Dtest=HackForTravisTest
