language: scala
scala:
    - 2.10.4
jdk:
    - oraclejdk7
#os:
#    - osx
before_install:
    - cat /proc/version
    - wget https://protobuf.googlecode.com/files/protobuf-2.4.1.tar.gz
    - tar -xzvf protobuf-2.4.1.tar.gz
    - cd protobuf-2.4.1 && ./configure --prefix=/usr && make && sudo make install
    - cd -
    - git clone https://github.com/eHarmony/aloha-proto.git
    - cd aloha-proto
    - mvn clean install
    - cd -
    - cat /proc/version
#install: mvn clean package -DskipTests=false
install: cat /proc/version && cd aloha-core &&  mvn clean test -Dtest=HackForTravisTest
